name: a1to5x

on:
  workflow_dispatch:
     inputs:
       mode:
         description: 'Download mode(aria2c,curl,axel,wget)'
         required: true
         default: 'aria2c'
       output:
         description: 'Output(wget=O)'
         required: true
         default: 'o'
       filename:
         description: 'ROM NAME'
         default: ''
       filelink:
         description: 'ROM LINK'
         required: true
       release:
         description: 'Upload to Release'
         required: true
         default: 'true'
       we:
         description: 'Upload to WeTransfer'
         required: true
         default: 'true'
       muse:
         description: 'Upload to MuseTransfer'
         required: true
         default: 'true'
       sed:
         description: 'Sed Mode(dd or i)'
         required: true
         default: 'dd'

jobs:
  a1to5x:
    runs-on: ubuntu-18.04
    continue-on-error: false

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Initialization environment
        run: |
          sudo apt-get update -y
          sudo apt-get install -y git wget curl aria2 python python3 python3-setuptools unzip axel cpio file
          pip3 install protobuf
          pip3 install gdown

      - id: var
        name: Download
        run: |
          echo "Download"
          if [[ ${{ github.event.inputs.filelink }} == *"drive.google.com"* ]]; then
              if [[ ${{ github.event.inputs.filelink }} == *"file"* ]]; then
                  DOWNLOAD_LINK1=$(echo ${{ github.event.inputs.filelink }} | cut -d / -f 6)
              elif [[ ${{ github.event.inputs.filelink }} == *"id"* ]]; then
                  DOWNLOAD_LINK1=$(echo ${{ github.event.inputs.filelink }} | cut -d = -f 2 | cut -d '&' -f 1)
                  DOWNLOAD_LINK2=$(echo ${{ github.event.inputs.filelink }} | cut -d = -f 4)
              fi
              gdown https://drive.google.com/uc?id=${DOWNLOAD_LINK1} || gdown https://drive.google.com/uc?id=${DOWNLOAD_LINK2}
          else
              if [[ ! -z "${{ github.event.inputs.filename }}" ]]; then
                  FILENAME="${{ github.event.inputs.filename }}"
                  ${{ github.event.inputs.mode }} ${{ github.event.inputs.filelink }} -${{ github.event.inputs.output }} "$FILENAME"
              else
                  ${{ github.event.inputs.mode }} ${{ github.event.inputs.filelink }}
              fi
          fi
          ls
          FILENAME="$(ls -lS * | head -1 | awk '{print $9}')"
          echo "FILENAME: $FILENAME"
          FILENAME=$(basename ${FILENAME})
          NAME=$(basename $FILENAME .zip)
          echo "::set-output name=filename::$FILENAME"
          echo "::set-output name=name::$NAME"

      - name: Payload Extracting
        run: |
          echo "Payload Extracting"
          unzip ${{ steps.var.outputs.filename }} payload.bin
          rm -rf ${{ steps.var.outputs.filename }}
          python3 update-payload-extractor/extract.py payload.bin --output_dir output/
          rm -rf payload.bin
          ls

      - name: Fstab Patching
        run: |
            echo "system"
            sudo mkdir system
            sudo mount output/system.img system
            cat system/system/vendor/etc/fstab.qcom
            fstab="system/system/vendor/etc/fstab.qcom"
            if [[ "${{ github.event.inputs.sed }}" == "i" ]]; then
                sudo sed -i 's/,slotselect//g' $fstab
                sudo sed -i 's/,verify//g' $fstab
                sudo sed -i 's/,avb//g' $fstab
                sudo sed -i 's/forceencrypt/encryptable/g' $fstab
                sudo sed -i 's/fileencryption=ice/encryptable=footer/g' $fstab
            elif [[ "${{ github.event.inputs.sed }}" == "dd" ]]; then
                sudo sed 's/,slotselect//g' $fstab | sudo dd of=$fstab conv=notrunc
                sudo sed 's/,verify//g' $fstab | sudo dd of=$fstab conv=notrunc
                sudo sed 's/,avb//g' $fstab | sudo dd of=$fstab conv=notrunc
                sudo sed 's/forceencrypt/encryptable/g' $fstab | sudo dd of=$fstab conv=notrunc
                sudo sed 's/fileencryption=ice/encryptable=footer/g' $fstab | sudo dd of=$fstab conv=notrunc
            fi
            cat system/system/vendor/etc/fstab.qcom
            sudo cp system/system/vendor/etc/fstab.qcom output/fstab.qcom
            sudo umount system
            sudo rm -rf system

      - name: Patching boot
        run: |
          echo "Patching boot"
          mv output/boot.img mkbootimg/
          cd mkbootimg
          ./mkboot boot.img boot
          rm boot.img
          cd boot
          ls
          sed -i 's/veritykeyid=id:\w*//g' img_info
          mv kernel image.gz-dtb
          ../split-appended-dtb image.gz-dtb
          rm image.gz-dtb
          ls
          for i in `find *.dtb`; do
            echo "$i"
            if [[ ! -z "$(../../fdtget $i /firmware/android/fstab -p 2>/dev/null || true)" ]]; then
                echo "true"
                ../../magiskboot dtb $i print -f
                ../../fdtget $i /firmware/android/vbmeta parts 2>/dev/null || true
                ../../fdtput $i -r /firmware/android/vbmeta
                ../../fdtput $i /firmware/android/fstab/system status ok -ts
                ../../fdtput $i /firmware/android/fstab/system fsmgr_flags wait -ts
                ../../fdtput $i /firmware/android/fstab/vendor fsmgr_flags wait -ts
                echo "列出android下的节点"
                ../../fdtget $i /firmware/android/vbmeta -l 2>/dev/null || true
                ../../fdtget $i /firmware/android/vbmeta parts 2>/dev/null || true
                ../../magiskboot dtb $i print -f
            fi
          done
          ls
          cat kernel *.dtb > image.gz-dtb
          rm -f *.dtb
          rm -f kernel
          mv image.gz-dtb kernel
          ls
          cd ..
          ./mkboot boot boot.img
          cd ..
          mv mkbootimg/boot.img ./
          ./magiskboot unpack -h boot.img
          cp -f cpio/ramdisk-sar.cpio ramdisk.cpio
          ./magiskboot repack boot.img
          mv new-boot.img output/boot.img
          ls -al
          
      - name: Packing
        run: |
          cp output/boot.img template/boot.img
          mv output/system.img template/system.img
          cd template
          ls -al
          echo "--------------------------------------------"
          zip -q -r -9 ${{ steps.var.outputs.filename }} *
          cd ..
          mv template/${{ steps.var.outputs.filename }} ./
          ls -al

      - name: Upload to Artifact
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: |
            output
          retention-days: 7

      - name: Upload to WeTransfer
        if: github.event.inputs.we == 'true'
        continue-on-error: true
        run: |
          echo "Upload to WeTransfer"
          curl -fsSL git.io/file-transfer | sh
          wetrans=$(./transfer wet -s -p 16 --no-progress ${{ steps.var.outputs.filename }})
          wetrans=$(echo $wetrans | grep -o -E "https[^ ]*")
          echo "WeTransfer: $wetrans"
          echo "WeTransfer: $wetrans" >> boby.txt

      - name: Upload to MuseTransfer
        if: github.event.inputs.muse == 'true'
        continue-on-error: true
        run: |
          echo "Upload to MuseTransfer"
          curl -fsSL git.io/file-transfer | sh
          musetrans=$(./transfer muse -s -p 12 --no-progress ${{ steps.var.outputs.filename }})
          musetrans=$(echo $musetrans | grep -o -E "https[^ ]*")
          echo "MuseTransfer: $musetrans"
          echo "MuseTransfer: $musetrans" >> boby.txt

      - name: Upload to Release
        if: github.event.inputs.release == 'true'
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.var.outputs.filename }}
          name: ${{ steps.var.outputs.name }}
          tag_name: ${{ github.run_id }}
          body_path: boby.txt
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE }}

